version: '3.9'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGODB_DATABASE="books-store"
    volumes:
      - mongo:/data/db

volumes:
  mongo:
